id: 5170010ca00646a2ad92b14bda9b6ca0
initial_creation_type: ocr
source_metadata:
  volumes:
    6061b5b372514da5813a9c36551a6db4:
      base_file: v025.txt
      image_group_id: I1PD95870
      title: ''
      total_pages: 1853
      volume_number: 25
